### ISSUE TITLE
No such table: tt Error

### ISSUE THREAD

**Issue by LDzik** [mah-hacker/Teams-Bot#1]
Traceback (most recent call last):
  File "D:\microsoft teams autojoin\Teams-Bot\msbot.py", line 251, in <module>
    add_timetable()
  File "D:\microsoft teams autojoin\Teams-Bot\msbot.py", line 99, in add_timetable
    c.execute("INSERT INTO tt VALUES ('%s','%s','%s','%s')"%(name,start_time,end_time,day))
sqlite3.OperationalError: no such table: tt

**Comment by mah-hacker** [comment]
Reach me @LDzik in instagram...@mohammed_althaf_h

**Comment by mohammed-althaf-h** [comment]
tt.db file was not created..try again and make sure it's in the same path as the msbot.py.. still same error reach me through mail or instagram.
email= althaf78602@gmail.com
instagram = mohammed_althaf_h
